cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask '1password'
cask 'alfred'
cask 'dash'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'helium'
cask 'hyper'
cask 'obs'
cask 'openemu'
cask 'postgres'
cask 'postico'
cask 'screenflick'
cask 'screenflow'
cask 'sketch'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'

